# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'post_admin_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import first1
import empManagement
import supplierManagement
from functools import partial

class Ui_Form3(object):

    '''def openFirstPage(self, FirstPage):
        self.windows_first= QtWidgets.QMainWindow()
        self.ui_first = first1.Ui_Form()
        self.ui_first.setupUi(self.windows_first)
        Form.close()
        self.windows_first.show()'''

    def first1(self):                             ##2
        self.window4 = QtWidgets.QMainWindow()
        self.ui = first1.Ui_Form()
        self.ui.setupUi(self.window4)   
        self.window4.show()    

    def empManagement(self):
        empManagement.Flag = True                             ##2
        self.window5 = QtWidgets.QMainWindow()
        self.ui = empManagement.Ui_ManageEmpWindow()
        self.ui.setupUi(self.window5)   
        self.window5.show()

    def supplierManagement(self):  
        supplierManagement.Flag = True                           ##2
        self.window6 = QtWidgets.QMainWindow()
        self.ui = supplierManagement.Ui_suppManagementWindow()
        self.ui.setupUi(self.window6)   
        self.window6.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1206, 897)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)       ##3        
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Form.setStyleSheet("QPushButton{\n"
"background-color:rgba(85,98,112,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:25px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgba(255,107,107,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(255,107,107,255):\n"
"backgound-position:calc(100% -10px)center:\n"
"}\n"
"\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 40, 1131, 741))
        self.label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:75px;\n"
"border-top-left-radius:75px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 40, 391, 741))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98,112, 255), stop:1 rgba(255, 107, 107, 255));\n"
"border-top-left-radius:75px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.manageEmp = QtWidgets.QPushButton(Form)
        self.manageEmp.setGeometry(QtCore.QRect(510, 340, 271, 181))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.manageEmp.setFont(font)
        self.manageEmp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageEmp.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.manageEmp.setStyleSheet("image: url(:/images/employees.png);\n"
"\n"
"")
        self.manageEmp.setText("")
        self.manageEmp.setObjectName("manageEmp")
        self.manageSupp = QtWidgets.QPushButton(Form)
        self.manageSupp.setGeometry(QtCore.QRect(870, 340, 271, 181))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.manageSupp.setFont(font)
        self.manageSupp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageSupp.setStyleSheet("image: url(:/images/supplier.png);\n"
"padding-left: 10%;\n"
"padding-top: 1%;\n"
"padding-right: 10%;\n"
"padding-bottom: 10%;")
        self.manageSupp.setText("")
        self.manageSupp.setObjectName("manageSupp")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 430, 391, 461))
        font = QtGui.QFont()
        font.setFamily("Mountain")
        font.setPointSize(210)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("color:rgba(255,107,107,255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        # self.pushButton_3 = QtWidgets.QPushButton(Form)
        # self.pushButton_3.setGeometry(QtCore.QRect(1160, 40, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        # self.pushButton_3.setFont(font)
        # self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        # self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(700, 50, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(550, 530, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(920, 530, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.logout = QtWidgets.QPushButton(Form)
        self.logout.setGeometry(QtCore.QRect(1030, 710, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.logout.setFont(font)
        self.logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout.setObjectName("logout")

        #self.pushButton_3.setObjectName("pushButton_3")
        #self.pushButton_3.clicked.connect(Form.close) 
        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.label_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.manageEmp.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.manageSupp.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.logout.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

        self.logout.clicked.connect(self.first1)
        self.logout.clicked.connect(Form.close)
        self.manageEmp.clicked.connect(self.empManagement)
        self.manageEmp.clicked.connect(Form.close)
        self.manageSupp.clicked.connect(self.supplierManagement)
        self.manageSupp.clicked.connect(Form.close)

        #self.logout.clicked.connect(partial(self.first1,Form))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "-"))
        #self.pushButton_3.setText(_translate("Form", "X"))
        self.label_3.setText(_translate("Form", "Admin Mode"))
        self.label_6.setText(_translate("Form", "Manage Employees"))
        self.label_7.setText(_translate("Form", "Manage Suppliers"))
        self.logout.setText(_translate("Form", "Log out"))
import res1

if __name__ == "__main__":                                    ##6
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form3()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
