# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'post_emp_login .ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import res
import second
import BillingSystem
import invManagement

class Ui_Form(object):

    def BillingSystem(self):
        BillingSystem.Flag = True                             
        self.window6 = QtWidgets.QMainWindow()
        self.ui = BillingSystem.Ui_ManageBilllWindow()
        self.ui.setupUi(self.window6)   
        self.window6.show()

    def second(self):                             
        self.window4 = QtWidgets.QMainWindow()
        self.ui = second.Ui_Form2()
        self.ui.setupUi(self.window4)   
        self.window4.show()    

    def invManagement(self):
        invManagement.Flag = True                             
        self.window5 = QtWidgets.QMainWindow()
        self.ui = invManagement.Ui_InvManagement()
        self.ui.setupUi(self.window5)   
        self.window5.show()    

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1206, 897)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)       ##3        
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Form.setStyleSheet("QPushButton{\n"
"background-color:rgba(85,98,112,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:25px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgba(255,107,107,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(255,107,107,255):\n"
"backgound-position:calc(100% -10px)center:\n"
"}\n"
"\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 40, 1131, 741))
        self.label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:75px;\n"
"border-top-left-radius:75px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 40, 391, 741))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98,112, 255), stop:1 rgba(255, 107, 107, 255));\n"
"border-top-left-radius:75px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.manageEmp = QtWidgets.QPushButton(Form)
        self.manageEmp.setGeometry(QtCore.QRect(510, 340, 271, 181))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.manageEmp.setFont(font)
        self.manageEmp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageEmp.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.manageEmp.setStyleSheet("image: url(:/images/inventory.png);\n"
"padding-left: 5%;\n"
"padding-top: 15%;\n"
"padding-right: 5%;\n"
"padding-bottom: 15%;")
        self.manageEmp.setText("")
        self.manageEmp.setObjectName("manageEmp")
        self.manageSupp = QtWidgets.QPushButton(Form)
        self.manageSupp.setGeometry(QtCore.QRect(870, 340, 271, 181))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.manageSupp.setFont(font)
        self.manageSupp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageSupp.setStyleSheet("image: url(:/images/bill.png);\n"
"padding-left: 5%;\n"
"padding-top: 10%;\n"
"padding-right: 5%;\n"
"padding-bottom: 12%;")
        self.manageSupp.setText("")
        self.manageSupp.setObjectName("manageSupp")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 430, 391, 461))
        font = QtGui.QFont()
        font.setFamily("Mountain")
        font.setPointSize(210)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("color:rgba(255,107,107,255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(680, 50, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(550, 530, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(940, 530, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.logout = QtWidgets.QPushButton(Form)
        self.logout.setGeometry(QtCore.QRect(1030, 710, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.logout.setFont(font)
        self.logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout.setObjectName("logout")

        self.logout.clicked.connect(self.second)
        self.logout.clicked.connect(Form.close)

        self.manageEmp.clicked.connect(self.invManagement)
        self.manageEmp.clicked.connect(Form.close)

        self.manageSupp.clicked.connect(self.BillingSystem)
        self.manageSupp.clicked.connect(Form.close)

        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.label_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.manageEmp.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.manageSupp.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.logout.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "-"))
        self.label_3.setText(_translate("Form", "Employee Mode"))
        self.label_6.setText(_translate("Form", "Manage Inventory"))
        self.label_7.setText(_translate("Form", "Generate Bill"))
        self.logout.setText(_translate("Form", "Log out"))


if __name__ == "__main__":                                    ##6
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
