# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'productquantity.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import time
import res
import sqlite3
import BillingSystem
pquantity = ""


class Ui_productQuantity(object):

    def billingsystem(self):                             
        self.window1 = QtWidgets.QMainWindow()
        self.ui = BillingSystem.Ui_ManageEmpWindow()
        self.ui.setupUi(self.window1)   
        self.window1.show()


    def showQuantity(self):
        connection = sqlite3.connect("db.db")
        result = connection.execute("""SELECT in_stock FROM product WHERE product_id = ?""",(BillingSystem.scannedbarcode_id,))
        resultlist = list(result.fetchall())
        global pquantity
        pquantity = str(resultlist[0][0])
        self.in_stock_lbl.setText("In Stock: " + pquantity )

    def insertIntoCart(self):
        connection = sqlite3.connect("db.db")
        try:
            result = connection.execute("""SELECT * FROM product WHERE product_id = ?""",(BillingSystem.scannedbarcode_id,))
            resultlist = list(result.fetchall())
            name = resultlist[0][1]
            category = resultlist[0][2]
            quantity = self.quantity_LE.text()
            rate = resultlist[0][5]
            amount = int(quantity)*int(rate)
            connection.execute("""INSERT into bill VALUES (?,?,?,?,?,?)""",(BillingSystem.current_bill,name,category,quantity,rate,amount))
            BillingSystem.scannedbarcode_id = ""
            BillingSystem.Flag2 = True
            BillingSystem.Flag2 = False
            connection.commit()
            
        except Exception as e:
            print(e)
        connection.close()
        
        


    def setupUi(self, productQuantity):
        productQuantity.setObjectName("productQuantity")
        productQuantity.resize(764, 443)
        productQuantity.setWindowFlags(QtCore.Qt.FramelessWindowHint)            
        productQuantity.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        productQuantity.setStyleSheet("QPushButton{\n"
"background-color:rgba(85,98,112,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:25px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgba(255,107,107,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(255,107,107,255):\n"
"backgound-position:calc(100% -10px)center:\n"
"}\n"
"")
        self.label = QtWidgets.QLabel(productQuantity)
        self.label.setGeometry(QtCore.QRect(10, 20, 711, 411))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:50px;\n"
"border-top-left-radius:50px;\n"
"border-top-right-radius:5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(productQuantity)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 271, 411))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98,112, 255), stop:1 rgba(255, 107, 107, 255));\n"
"border-top-left-radius:50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.quantity_LE = QtWidgets.QLineEdit(productQuantity)
        self.quantity_LE.setGeometry(QtCore.QRect(360, 120, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.quantity_LE.setFont(font)
        self.quantity_LE.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"")
        self.quantity_LE.setText("")
        self.quantity_LE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.quantity_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity_LE.setPlaceholderText("")
        self.quantity_LE.setObjectName("quantity_LE")
        self.add_btn = QtWidgets.QPushButton(productQuantity)
        self.add_btn.setGeometry(QtCore.QRect(430, 200, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.add_btn.setFont(font)
        self.add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_btn.setMouseTracking(False)
        self.add_btn.setTabletTracking(False)
        self.add_btn.setStyleSheet("border-radius:15px;")
        self.add_btn.setObjectName("add_btn")
        self.label_4 = QtWidgets.QLabel(productQuantity)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 271, 251))
        font = QtGui.QFont()
        font.setFamily("Mountain")
        font.setPointSize(150)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255,107,107,255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.in_stock_lbl = QtWidgets.QLabel(productQuantity)
        self.in_stock_lbl.setGeometry(QtCore.QRect(380, 280, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.in_stock_lbl.setFont(font)
        self.in_stock_lbl.setStyleSheet("color: #6B6B6B;")
        self.in_stock_lbl.setText("")
        self.in_stock_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.in_stock_lbl.setWordWrap(False)
        self.in_stock_lbl.setObjectName("in_stock_lbl")
        self.error_lbl = QtWidgets.QLabel(productQuantity)
        self.error_lbl.setGeometry(QtCore.QRect(330, 330, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.error_lbl.setFont(font)
        self.error_lbl.setStyleSheet("color: #6B6B6B;")
        self.error_lbl.setText("")
        self.error_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.error_lbl.setWordWrap(False)
        self.error_lbl.setObjectName("error_lbl")
        self.label_5 = QtWidgets.QLabel(productQuantity)
        self.label_5.setGeometry(QtCore.QRect(410, 60, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(0,0,0,200);\n"
"")
        self.label_5.setObjectName("label_5")

        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.label_5.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.add_btn.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))


        self.showQuantity()
        self.add_btn.clicked.connect(self.insertIntoCart)
        self.add_btn.clicked.connect(BillingSystem.Ui_ManageEmpWindow.loadBillData)
        self.add_btn.clicked.connect(productQuantity.close)
        

        

        self.retranslateUi(productQuantity)
        QtCore.QMetaObject.connectSlotsByName(productQuantity)



    def retranslateUi(self, productQuantity):
        _translate = QtCore.QCoreApplication.translate
        productQuantity.setWindowTitle(_translate("productQuantity", "Form"))
        self.add_btn.setText(_translate("productQuantity", "Add"))
        self.label_4.setText(_translate("productQuantity", "-"))
        self.label_5.setText(_translate("productQuantity", "Enter Quantity"))

if __name__ == "__main__":                                    
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_productQuantity()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())