# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_Supplier.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import sqlite3
import res
import supplierManagement
from datetime import datetime

check = True
dt = datetime.today().strftime('%d-%m-%Y')



class Ui_addEmp_Window(object):

    def suppManagement(self):                             ##2
        self.window3 = QtWidgets.QMainWindow()
        self.ui = supplierManagement.Ui_suppManagementWindow()
        self.ui.setupUi(self.window3)
        self.window3.show()

    def preloadData(self):
        connection = sqlite3.connect("db.db")
        result = connection.execute("""SELECT * FROM supplier WHERE suppID = ?""",(supplierManagement.suppIdGlobal,))
        supplist = list(result.fetchall())
        self.suppID_LE.setText(supplist[0][0])
        self.name_LE.setText(supplist[0][1])
        self.contact_LE.setText(supplist[0][2])
        self.product_cat_LE.setText(supplist[0][3])
        self.payment_due_LE.setText(supplist[0][4])
        self.last_payment_date_LE.setText(supplist[0][5])
        self.address_LE.setText(supplist[0][6])
        connection.close()


    def allFieldsValidation(self):
        suppId = self.suppID_LE.text()
        name = self.name_LE.text()
        contact = self.contact_LE.text()
        product_cat = self.product_cat_LE.text()
        payment_due = self.payment_due_LE.text()
        last_payment_date = self.last_payment_date_LE.text()
        address = self.address_LE.text()
        if ((suppId != "" and  suppId.isspace() == False) and (name != "" and  name.isspace() == False) and (contact != "" and  contact.isspace() == False) and (product_cat != "" and  product_cat.isspace() == False)  and (address != "" and  address.isspace() == False)):
                return True
        else:
                self.label_5.setGeometry(QtCore.QRect(690, 680, 421, 91))
                self.label_5.setText("All fields are required ")
                return False

    def setupUi(self, addEmp_Window):
        addEmp_Window.setObjectName("addEmp_Window")
        addEmp_Window.resize(1350, 833)
        addEmp_Window.setWindowFlags(QtCore.Qt.FramelessWindowHint)            
        addEmp_Window.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        addEmp_Window.setStyleSheet("QPushButton{\n"
"background-color:rgba(85,98,112,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:25px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgba(255,107,107,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(255,107,107,255):\n"
"backgound-position:calc(100% -10px)center:\n"
"}\n"
"")
        self.label = QtWidgets.QLabel(addEmp_Window)
        self.label.setGeometry(QtCore.QRect(130, 30, 1131, 771))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:50px;\n"
"border-top-left-radius:50px;\n"
"border-top-right-radius:5px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(addEmp_Window)
        self.label_2.setGeometry(QtCore.QRect(130, 30, 381, 771))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98,112, 255), stop:1 rgba(255, 107, 107, 255));\n"
"border-top-left-radius:50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(addEmp_Window)
        self.label_3.setGeometry(QtCore.QRect(670, 50, 441, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #000;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.suppID_LE = QtWidgets.QLineEdit(addEmp_Window)
        self.suppID_LE.setGeometry(QtCore.QRect(560, 190, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.suppID_LE.setFont(font)
        self.suppID_LE.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.suppID_LE.setText("")
        self.suppID_LE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.suppID_LE.setObjectName("suppID_LE")
        self.contact_LE = QtWidgets.QLineEdit(addEmp_Window)
        self.contact_LE.setGeometry(QtCore.QRect(560, 290, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.contact_LE.setFont(font)
        self.contact_LE.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.contact_LE.setText("")
        self.contact_LE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.contact_LE.setObjectName("contact_LE")
        self.pushButton = QtWidgets.QPushButton(addEmp_Window)
        self.pushButton.setGeometry(QtCore.QRect(810, 600, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setTabletTracking(False)
        self.pushButton.setStyleSheet("border-radius:15px;")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(addEmp_Window)
        self.label_4.setGeometry(QtCore.QRect(130, 400, 381, 541))
        font = QtGui.QFont()
        font.setFamily("Mountain")
        font.setPointSize(210)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255,107,107,255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.address_LE = QtWidgets.QLineEdit(addEmp_Window)
        self.address_LE.setGeometry(QtCore.QRect(560, 490, 661, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.address_LE.setFont(font)
        self.address_LE.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.address_LE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.address_LE.setObjectName("address_LE")
        self.product_cat_LE = QtWidgets.QLineEdit(addEmp_Window)
        self.product_cat_LE.setGeometry(QtCore.QRect(910, 290, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.product_cat_LE.setFont(font)
        self.product_cat_LE.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.product_cat_LE.setText("")
        self.product_cat_LE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.product_cat_LE.setObjectName("product_cat_LE")
        self.name_LE = QtWidgets.QLineEdit(addEmp_Window)
        self.name_LE.setGeometry(QtCore.QRect(910, 190, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.name_LE.setFont(font)
        self.name_LE.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.name_LE.setText("")
        self.name_LE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.name_LE.setObjectName("name_LE")
        self.last_payment_date_LE = QtWidgets.QLineEdit(addEmp_Window)
        self.last_payment_date_LE.setGeometry(QtCore.QRect(910, 390, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.last_payment_date_LE.setFont(font)
        self.last_payment_date_LE.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.last_payment_date_LE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.last_payment_date_LE.setObjectName("last_payment_date_LE")
        self.payment_due_LE = QtWidgets.QLineEdit(addEmp_Window)
        self.payment_due_LE.setGeometry(QtCore.QRect(560, 390, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.payment_due_LE.setFont(font)
        self.payment_due_LE.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.payment_due_LE.setText("")
        self.payment_due_LE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.payment_due_LE.setObjectName("payment_due_LE")
        self.pushButton_2 = QtWidgets.QPushButton(addEmp_Window)
        self.pushButton_2.setGeometry(QtCore.QRect(1200, 30, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("font-size:20px;\n"
"image: url(:/images/back2.png);\n"
"text-align: center;\n"
"border-radius:5px;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(addEmp_Window)
        self.label_5.setGeometry(QtCore.QRect(740, 680, 421, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #6B6B6B;")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(addEmp_Window)
        self.label_6.setGeometry(QtCore.QRect(670, 690, 91, 71))
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")

        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.label_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.pushButton_2.clicked.connect(self.suppManagement)
        self.pushButton_2.clicked.connect(addEmp_Window.close)
        self.last_payment_date_LE.setEnabled(False)
        self.suppID_LE.setEnabled(False)
        self.preloadData()
        self.pushButton.clicked.connect(self.passage)

        self.retranslateUi(addEmp_Window)
        QtCore.QMetaObject.connectSlotsByName(addEmp_Window)

    def retranslateUi(self, addEmp_Window):
        _translate = QtCore.QCoreApplication.translate
        addEmp_Window.setWindowTitle(_translate("addEmp_Window", "Form"))
        self.label.setText(_translate("addEmp_Window", "TextLabel"))
        self.label_3.setText(_translate("addEmp_Window", "UPDATE SUPPLIER"))
        self.suppID_LE.setPlaceholderText(_translate("addEmp_Window", "Supplier ID"))
        self.contact_LE.setPlaceholderText(_translate("addEmp_Window", "Contact No."))
        self.pushButton.setText(_translate("addEmp_Window", "Submit"))
        self.label_4.setText(_translate("addEmp_Window", "-"))
        self.address_LE.setPlaceholderText(_translate("addEmp_Window", "Address"))
        self.product_cat_LE.setPlaceholderText(_translate("addEmp_Window", "Product Category"))
        self.name_LE.setPlaceholderText(_translate("addEmp_Window", "Name"))
        self.last_payment_date_LE.setPlaceholderText(_translate("addEmp_Window", "Last Payment Date"))
        self.payment_due_LE.setPlaceholderText(_translate("addEmp_Window", "Payment Due"))
        global check
        check = True
        if(check):
                global x
                x = addEmp_Window
                check = False
       
    def passage(self):
        self.updSupp(x)

    def updSupp(self,x):
        suppID = self.suppID_LE.text()
        name = self.name_LE.text()
        contact = self.contact_LE.text()
        product_cat = self.product_cat_LE.text()
        payment_due = self.payment_due_LE.text()
        last_payment_date = self.last_payment_date_LE.text()
        address = self.address_LE.text()

        connection = sqlite3.connect("db.db")

        if (self.allFieldsValidation()):
                if any(chr.isdigit() for chr in name):
                        self.label_5.setGeometry(QtCore.QRect(690, 680, 421, 91))
                        self.label_5.setText("Enter valid Name")
                        self.label_6.setStyleSheet("")

                elif (len(contact)!= 10 or contact.isdigit() == False):
                        self.label_5.setGeometry(QtCore.QRect(690, 680, 421, 91))
                        self.label_5.setText("Enter Valid Contact No.")
                        self.label_6.setStyleSheet("")
                
                elif (payment_due.isspace()):
                        self.label_5.setGeometry(QtCore.QRect(690, 680, 421, 91))
                        self.label_5.setText("Invalid Payment Due")
                        self.label_6.setStyleSheet("")
                
                elif (last_payment_date.isspace()):
                        self.label_5.setGeometry(QtCore.QRect(690, 680, 421, 91))
                        self.label_5.setText("Invalid Last Payment Date")
                        self.label_6.setStyleSheet("")
                else:
                        pdue = connection.execute("""SELECT payment_due from supplier WHERE suppID = ? """,[suppID])
                        pdue_result = list(pdue.fetchall())
                        final_pdue = pdue_result[0][0]
                        if(payment_due>=final_pdue):
                                #Date will not be update
                                connection.execute("""UPDATE supplier SET  name = ?, contact = ?, product_category = ?, payment_due = ?, address =? WHERE suppID = ?""",(name,contact,product_cat,payment_due,address,supplierManagement.suppIdGlobal))
                                connection.commit()
                                self.label_5.setGeometry(QtCore.QRect(690, 680, 421, 91))
                                self.label_5.setText("Update Successful")
                                self.label_6.setStyleSheet("image: url(:/img/success-icon-23194.png);")
                        else:
                                #Date will be updated
                                connection.execute("""UPDATE supplier SET  name = ?, contact = ?, product_category = ?, payment_due = ?, last_payment_date = ?, address =? WHERE suppID = ?""",(name,contact,product_cat,payment_due,dt,address,supplierManagement.suppIdGlobal))
                                connection.commit()
                                self.label_5.setGeometry(QtCore.QRect(690, 680, 421, 91))
                                self.label_5.setText("Update Successful")
                                self.label_6.setStyleSheet("image: url(:/img/success-icon-23194.png);")
                        #self.pushButton.setEnabled(False)
                        #time.sleep(5)
                        #x.close()
        
        connection.close()

if __name__ == "__main__":                                    ##6
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_addEmp_Window()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())